In [1]:
import os
import glob
import time
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [4]:
base_poi = pd.read_csv("../data/0_source_data/base_poi.zip",
                              compression='zip',
                              sep='\t'
                             )
base_poi

BaseID  Medical care  Hotel  Business affairs  Life service  Transportation hub  Culture  Sports  Residence  Entertainment and leisure  Scenic spot  Government  Factory  Shopping  Restaurant  Education  Landmark  Other
0          0             1      3                 4             1                   0        0       0         54                          0            0           1        0         6           6          2         0      4
1          1             0      0                 0             0                   0        0       0         27                          0            0           1        0         0           0          1         2      0
2          2             0      0                12             0                   1        0       0          3                          0            0           1        0         1           0          0         0      0
3          3             0      0                 0             0                   0        1       0          0                          0            1           0        0         0           0          0         0      0
4          4             0      0                 0             0                   0        0       0          4                          0            3           0        0         0           1          0         0      0
...      ...           ...    ...               ...           ...                 ...      ...     ...        ...                        ...          ...         ...      ...       ...         ...        ...       ...    ...
9846    9846             0      2                 0             0                   0        4       0          1                          0            0           2        0         0           0          0         0      0
9847    9847             0      0                 2             0                   0        2       0          0                          0            2           2        0         0           0          0         0      0
9848    9848             0      0                16             0                   0        0       0          3                          0            0           1        0         2           2          1         0      1
9849    9849             0      0                 1             0                   0        0       0         13                          0            0           0        0         0           3          2         0      0
9850    9850             0      5                 0             0                   0        0       0         29                          0            0           1        0         2           0          0         1      0

[9851 rows x 18 columns]

In [7]:
base_poi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9851 entries, 0 to 9850
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   BaseID                     9851 non-null   int64
 1   Medical care               9851 non-null   int64
 2   Hotel                      9851 non-null   int64
 3   Business affairs           9851 non-null   int64
 4   Life service               9851 non-null   int64
 5   Transportation hub         9851 non-null   int64
 6   Culture                    9851 non-null   int64
 7   Sports                     9851 non-null   int64
 8   Residence                  9851 non-null   int64
 9   Entertainment and leisure  9851 non-null   int64
 10  Scenic spot                9851 non-null   int64
 11  Government                 9851 non-null   int64
 12  Factory                    9851 non-null   int64
 13  Shopping                   9851 non-null   int64
 14  Restaurant              

In [6]:
# Schema overview
df = base_poi
for col in df.columns:
    
    print('=======================', col, '=======================')
    print('Unique values --> ', df[col].nunique())
    if (df[col].nunique() <= 30):
        print(df[col].unique())
        print('Distribution: ')
        print(df[col].value_counts())
    else:
        print(df[col].unique()[:5], '...')
    print()

======================= BaseID =======================
Unique values -->  9851
[0 1 2 3 4] ...

======================= Medical care =======================
Unique values -->  48
[1 0 2 4 5] ...

======================= Hotel =======================
Unique values -->  55
[3 0 1 2 4] ...

======================= Business affairs =======================
Unique values -->  201
[ 4  0 12  6  3] ...

======================= Life service =======================
Unique values -->  52
[ 1  0  2  8 26] ...

======================= Transportation hub =======================
Unique values -->  14
[ 0  1  4  2  3 30 19  5  8  7  9  6 15 18]
Distribution: 
0     9164
1      429
2      161
3       44
4       24
5       10
6        7
8        3
7        3
9        2
18       1
19       1
30       1
15       1
Name: Transportation hub, dtype: int64

======================= Culture =======================
Unique values -->  34
[0 1 2 3 6] ...

======================= Sports =======================
Uniq